# Generated by Django 3.1.5 on 2021-01-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(verbose_name='тип пользователя')),
                ('name', models.CharField(max_length=100, verbose_name='имя пользователя')),
                ('surname', models.CharField(max_length=100, verbose_name='фамилия пользователя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='отчество пользователя')),
                ('male', models.CharField(max_length=1, verbose_name='гендер пользователя')),
                ('email', models.CharField(max_length=100, verbose_name='email пользователя')),
                ('birthday', models.DateField(verbose_name='день рождения пользователя')),
                ('login', models.CharField(max_length=100, verbose_name='логин пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='пароль пользователя')),
            ],
        ),
    ]
