# Generated by Django 3.1.5 on 2021-01-08 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_title', models.CharField(max_length=200, verbose_name='название')),
                ('weather_text', models.TextField(verbose_name='текст')),
                ('date', models.DateTimeField(verbose_name='дата')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='имя автора')),
                ('comment_text', models.TextField(verbose_name='комментарий')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weather')),
            ],
        ),
    ]
