# Generated by Django 3.1.5 on 2021-07-10 15:54

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('weather', '0002_auto_20210110_0004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertice',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='day',
            name='news_id',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of the city'),
        ),
        migrations.AlterField(
            model_name='city',
            name='popolation',
            field=models.CharField(max_length=100, verbose_name='Population'),
        ),
        migrations.AlterField(
            model_name='city',
            name='square',
            field=models.CharField(max_length=100, verbose_name='Square'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='c_average',
            field=models.IntegerField(verbose_name='The average intensity od clouds'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='c_day',
            field=models.IntegerField(verbose_name='The intensity od clouds at the day'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='c_evening',
            field=models.IntegerField(verbose_name='The intensity od clouds in the evening'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='c_morning',
            field=models.IntegerField(verbose_name='The intensity od clouds in the morning'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='c_name_average',
            field=models.CharField(max_length=100, verbose_name='The average type of clouds'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='c_name_day',
            field=models.CharField(max_length=100, verbose_name='The type of clouds at the day'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='c_name_evening',
            field=models.CharField(max_length=100, verbose_name='The type of clouds in the evening'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='c_name_morning',
            field=models.CharField(max_length=100, verbose_name='The type of clouds in the morning'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='c_name_night',
            field=models.CharField(max_length=100, verbose_name='The type of clouds at the night'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='c_night',
            field=models.IntegerField(verbose_name='The intensity od clouds at the night'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='date',
            field=models.DateField(verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='id_district',
            field=models.IntegerField(verbose_name='id of the district'),
        ),
        migrations.AlterField(
            model_name='cloudy_icon',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='The way to the icon'),
        ),
        migrations.AlterField(
            model_name='cloudy_icon',
            name='name',
            field=models.CharField(max_length=100, verbose_name='The name of clouds'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of the country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='popolation',
            field=models.CharField(max_length=100, verbose_name='Population'),
        ),
        migrations.AlterField(
            model_name='country',
            name='square',
            field=models.CharField(max_length=100, verbose_name='Square'),
        ),
        migrations.AlterField(
            model_name='day',
            name='average_cloud',
            field=models.IntegerField(verbose_name='The average intensity od clouds'),
        ),
        migrations.AlterField(
            model_name='day',
            name='average_humidity',
            field=models.IntegerField(verbose_name='Average humidity'),
        ),
        migrations.AlterField(
            model_name='day',
            name='average_precipitation',
            field=models.IntegerField(verbose_name='the average type of precipitation'),
        ),
        migrations.AlterField(
            model_name='day',
            name='average_pressure',
            field=models.IntegerField(verbose_name='Average pressure'),
        ),
        migrations.AlterField(
            model_name='day',
            name='average_temperature',
            field=models.IntegerField(verbose_name='Average temperature'),
        ),
        migrations.AlterField(
            model_name='day',
            name='average_wind',
            field=models.IntegerField(verbose_name='Average wind'),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='day',
            name='icon_cloud',
            field=models.CharField(max_length=100, verbose_name='The way to the icon of cloud'),
        ),
        migrations.AlterField(
            model_name='day',
            name='icon_precipitation',
            field=models.CharField(max_length=100, verbose_name='The way to the icon of precipitation'),
        ),
        migrations.AlterField(
            model_name='day',
            name='name_cloud',
            field=models.CharField(max_length=100, verbose_name='The average type of clouds'),
        ),
        migrations.AlterField(
            model_name='day',
            name='name_precipitation',
            field=models.CharField(max_length=100, verbose_name='The name of precipitation'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of the district'),
        ),
        migrations.AlterField(
            model_name='district',
            name='popolation',
            field=models.CharField(max_length=100, verbose_name='Population'),
        ),
        migrations.AlterField(
            model_name='district',
            name='square',
            field=models.CharField(max_length=100, verbose_name='Square'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='date',
            field=models.DateField(verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='h_average',
            field=models.IntegerField(verbose_name='Average humidity'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='h_day',
            field=models.IntegerField(verbose_name='Humidity at the day'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='h_evening',
            field=models.IntegerField(verbose_name='Humidity in the evening'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='h_morning',
            field=models.IntegerField(verbose_name='Humidity in the morning'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='h_night',
            field=models.IntegerField(verbose_name='Humidity at the night'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='id_district',
            field=models.IntegerField(verbose_name='id of the district'),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='date',
            field=models.DateField(verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='id_district',
            field=models.IntegerField(verbose_name='id of the district'),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='p_average',
            field=models.IntegerField(verbose_name='The average quality of precipitation'),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='p_day',
            field=models.IntegerField(verbose_name='The quality of precipitation at the day'),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='p_evening',
            field=models.IntegerField(verbose_name='The quality of precipitation in the evening'),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='p_morning',
            field=models.IntegerField(verbose_name='The quality of precipitation in the morning'),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='p_name_average',
            field=models.CharField(max_length=100, verbose_name='the average type of precipitation'),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='p_name_day',
            field=models.CharField(max_length=100, verbose_name='The type of precipitation at the day'),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='p_name_evening',
            field=models.CharField(max_length=100, verbose_name='The type of precipitation in the evening'),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='p_name_morning',
            field=models.CharField(max_length=100, verbose_name='The type of precipitation in the morning'),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='p_name_night',
            field=models.CharField(max_length=100, verbose_name='The type of precipitation at the night'),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='p_night',
            field=models.IntegerField(verbose_name='The quality of precipitation at the night'),
        ),
        migrations.AlterField(
            model_name='precipitation_icon',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='The way to the icon'),
        ),
        migrations.AlterField(
            model_name='precipitation_icon',
            name='name',
            field=models.CharField(max_length=100, verbose_name='The name of precipitation'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='date',
            field=models.DateField(verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='id_district',
            field=models.IntegerField(verbose_name='id of the district'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='pressure_average',
            field=models.IntegerField(verbose_name='Average pressure'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='pressure_day',
            field=models.IntegerField(verbose_name='Pressure at the day'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='pressure_evening',
            field=models.IntegerField(verbose_name='Pressure in the evening'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='pressure_morning',
            field=models.IntegerField(verbose_name='Pressure in the morning'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='pressure_night',
            field=models.IntegerField(verbose_name='Pressure at the night'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateField(verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='id_district',
            field=models.IntegerField(verbose_name='id of the district'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='t_average',
            field=models.IntegerField(null=True, verbose_name='Average temperature'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='t_day',
            field=models.IntegerField(verbose_name='Temperature at the day'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='t_evening',
            field=models.IntegerField(verbose_name='Temperature in the evening'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='t_morning',
            field=models.IntegerField(verbose_name='Temperature in the morning'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='t_night',
            field=models.IntegerField(verbose_name='Temperature at the night'),
        ),
        migrations.AlterField(
            model_name='wind',
            name='date',
            field=models.DateField(verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='wind',
            name='id_district',
            field=models.IntegerField(verbose_name='id of the district'),
        ),
        migrations.AlterField(
            model_name='wind',
            name='w_average',
            field=models.IntegerField(verbose_name='Average wind'),
        ),
        migrations.AlterField(
            model_name='wind',
            name='w_day',
            field=models.IntegerField(verbose_name='Wind at the day'),
        ),
        migrations.AlterField(
            model_name='wind',
            name='w_evening',
            field=models.IntegerField(verbose_name='Wind in the evening'),
        ),
        migrations.AlterField(
            model_name='wind',
            name='w_morning',
            field=models.IntegerField(verbose_name='Wind in the morning'),
        ),
        migrations.AlterField(
            model_name='wind',
            name='w_night',
            field=models.IntegerField(verbose_name='Wind at the night'),
        ),
        migrations.DeleteModel(
            name='New',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
