# Generated by Django 3.1.5 on 2021-07-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertice',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='advertice',
            name='firm_name',
            field=models.CharField(max_length=100, verbose_name='Name of the firm'),
        ),
        migrations.AlterField(
            model_name='advertice',
            name='heading',
            field=models.TextField(verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='advertice',
            name='picture',
            field=models.CharField(max_length=100, verbose_name='Way to the picture'),
        ),
        migrations.AlterField(
            model_name='advertice',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='new',
            name='heading',
            field=models.TextField(verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='new',
            name='picture',
            field=models.CharField(max_length=100, verbose_name='Way to the picture'),
        ),
        migrations.AlterField(
            model_name='new',
            name='source',
            field=models.CharField(max_length=100, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='new',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject of the News'),
        ),
    ]
